export type Category =
  | "sours"
  | "spirit-forward"
  | "ancestral"
  | "highballs"
  | "fizz"
  | "tiki"
  | "duos-trios"
  | "sparkling"
  | "hot"
  | "flips-nogs";

export type Cocktail = {
  name: string;
  category: Category;
  ingredients: string[];
  method: string;
  glass: string;
  garnish: string;
  tip: string;
};

export const CATEGORIES: Record<Category, { label: string; description: string; color: string }> = {
  sours: {
    label: "Sours",
    description: "The backbone of modern cocktail making. Spirit + fresh citrus + sweetener in balance. Master the ratio and you can build almost any sour on the fly.",
    color: "#f5a623",
  },
  "spirit-forward": {
    label: "Spirit-Forward",
    description: "The spirit is the star. Blended with vermouth or fortified wine and always stirred — never shaken — to preserve a silky, clear texture.",
    color: "#4a90d9",
  },
  ancestral: {
    label: "Ancestral / Old Fashioned",
    description: "One of the oldest formats in cocktail history. Spirit, sugar, bitters and dilution. Nothing extra. Precision and restraint define this style.",
    color: "#8b5e3c",
  },
  highballs: {
    label: "Highballs & Collins",
    description: "Spirit over ice in a tall glass, topped with a carbonated mixer. Refreshing, versatile and among the most-ordered drinks in any venue.",
    color: "#5cb85c",
  },
  fizz: {
    label: "Fizz",
    description: "A sour extended with soda water, served without ice. Silver Fizz adds egg white for a creamy foam top. Technique-driven and highly satisfying to execute well.",
    color: "#9b59b6",
  },
  tiki: {
    label: "Tiki & Tropical",
    description: "Bold, layered and theatrical. Typically rum-based with fruit juices, spices and syrups. Often served in oversized or decorative glassware.",
    color: "#e74c3c",
  },
  "duos-trios": {
    label: "Duos & Trios",
    description: "A Duo is spirit plus liqueur. Add cream and it becomes a Trio. Simple builds where the quality and ratio of each ingredient determines everything.",
    color: "#1abc9c",
  },
  sparkling: {
    label: "Champagne & Sparkling",
    description: "Champagne or sparkling wine as a key component. Light, celebratory and versatile. Technique is gentle — always add sparkling last to preserve the bubbles.",
    color: "#f39c12",
  },
  hot: {
    label: "Hot Cocktails",
    description: "Served warm, these drinks provide comfort and richness. Temperature management and glassware preparation are the most important techniques.",
    color: "#e67e22",
  },
  "flips-nogs": {
    label: "Flips & Nogs",
    description: "Rich, indulgent drinks built around whole eggs or egg components, dairy and sweetener. A vigorous shake emulsifies everything into something deeply satisfying.",
    color: "#7f8c8d",
  },
};

export const COCKTAILS: Cocktail[] = [
  // ─── SOURS ───────────────────────────────────────────────────────────────
  {
    name: "Classic Daiquiri",
    category: "sours",
    ingredients: ["60ml white rum", "25ml fresh lime juice", "15ml sugar syrup"],
    method: "Shake hard with ice and double strain into a chilled glass.",
    glass: "Coupe",
    garnish: "Lime wheel on the rim",
    tip: "Fresh lime only — never bottled. The 2:1:¾ ratio is your baseline; adjust sweetness daily based on the lime's acidity. A well-made Daiquiri is one of the clearest indicators of a bartender's skill.",
  },
  {
    name: "Margarita",
    category: "sours",
    ingredients: ["50ml silver tequila", "25ml fresh lime juice", "20ml triple sec"],
    method: "Shake with ice and strain into a chilled glass with a salt rim.",
    glass: "Coupe or Margarita glass",
    garnish: "Salt rim (half-salted), lime wedge",
    tip: "Always ask before salting the rim — never assume. A spicy Margarita with jalapeño-infused tequila is an easy and natural upsell conversation. Half-salt the rim so guests have a choice with every sip.",
  },
  {
    name: "Whiskey Sour",
    category: "sours",
    ingredients: ["50ml bourbon", "25ml fresh lemon juice", "15ml sugar syrup", "20ml egg white (optional)"],
    method: "If using egg white, dry shake first without ice, then shake again with ice. Double strain.",
    glass: "Rocks",
    garnish: "Lemon slice, cocktail cherry, a few dashes of Angostura on the foam",
    tip: "The dry shake is non-negotiable for a proper foam. Show guests who say no to egg white what the texture looks like — most change their mind. The Angostura dashes on the foam are both visual and aromatic.",
  },
  {
    name: "Amaretto Sour",
    category: "sours",
    ingredients: ["45ml amaretto", "30ml fresh lemon juice", "15ml bourbon", "20ml egg white"],
    method: "Dry shake all ingredients first, then shake with ice and double strain.",
    glass: "Rocks",
    garnish: "Lemon slice, cocktail cherry",
    tip: "The bourbon is a bartender's trick — it adds structure and cuts the sweetness of the amaretto without guests noticing. Most will say it tastes far better than they expected. Worth mentioning as a selling point.",
  },
  {
    name: "Cosmopolitan",
    category: "sours",
    ingredients: ["40ml citrus vodka", "15ml triple sec", "15ml fresh lime juice", "30ml cranberry juice"],
    method: "Shake with ice and fine strain into a chilled glass.",
    glass: "Martini",
    garnish: "Flamed orange peel",
    tip: "Cranberry is a colour and balance agent, not the dominant flavour — go light on it. Flaming the orange peel adds theatre and aroma in under ten seconds. Do it tableside whenever possible; guests remember it.",
  },
  {
    name: "Gimlet",
    category: "sours",
    ingredients: ["60ml gin", "20ml fresh lime juice", "15ml sugar syrup"],
    method: "Shake with ice and double strain, or stir if using lime cordial.",
    glass: "Coupe",
    garnish: "Lime wheel",
    tip: "Traditionalists use Rose's lime cordial instead of fresh juice and sugar — no shaking required. The fresh version is sharper and more vibrant. Know both; some guests will have a strong preference for one over the other.",
  },
  {
    name: "Pisco Sour",
    category: "sours",
    ingredients: ["60ml pisco", "30ml fresh lime juice", "20ml sugar syrup", "20ml egg white", "2 dashes Angostura bitters"],
    method: "Dry shake without ice first, then shake with ice and double strain.",
    glass: "Rocks or coupe",
    garnish: "3 drops Angostura bitters placed on the foam",
    tip: "The bitters on the foam are fragrance, not just decoration. Encourage guests to smell the drink before their first sip. A great conversation piece for explaining pisco's Peruvian and Chilean origins.",
  },
  {
    name: "Clover Club",
    category: "sours",
    ingredients: ["45ml gin", "20ml fresh lemon juice", "15ml raspberry syrup", "20ml egg white"],
    method: "Dry shake, then shake hard with ice and double strain.",
    glass: "Coupe",
    garnish: "3 fresh raspberries",
    tip: "A pre-Prohibition classic from Philadelphia. The pink colour makes it approachable; the gin and lemon deliver real sophistication. An excellent gateway cocktail for guests who say they don't enjoy gin.",
  },
  {
    name: "New York Sour",
    category: "sours",
    ingredients: ["50ml bourbon", "25ml fresh lemon juice", "15ml sugar syrup", "15ml egg white", "15ml full-bodied red wine (float)"],
    method: "Dry shake, then shake with ice. Strain into the glass. Float red wine gently over the back of a bar spoon.",
    glass: "Rocks",
    garnish: "Lemon slice, dehydrated orange half-wheel",
    tip: "The wine float changes as the guest drinks — they get two experiences in one glass. Always tell guests before they stir it. The visual is striking and makes this one of the easiest cocktails to recommend.",
  },

  // ─── SPIRIT-FORWARD ──────────────────────────────────────────────────────
  {
    name: "Dry Martini",
    category: "spirit-forward",
    ingredients: ["60ml gin or vodka", "10–15ml dry vermouth"],
    method: "Stir with ice for around 30 seconds and strain into a pre-chilled glass.",
    glass: "Martini",
    garnish: "Lemon twist or olive — always ask the guest",
    tip: "The Martini is one of the most personal cocktails you will make. Ask: gin or vodka, olive or twist, dirty or clean, and how dry. Never assume. Stirring keeps the texture silky — a shaken Martini is technically wrong and clouds the drink.",
  },
  {
    name: "Negroni",
    category: "spirit-forward",
    ingredients: ["30ml gin", "30ml sweet vermouth", "30ml Campari"],
    method: "Stir with ice until well chilled and strain over a large ice cube.",
    glass: "Rocks",
    garnish: "Orange peel, expressed and placed on the rim or in the glass",
    tip: "Equal parts is one of the easiest spec ratios to memorise. Campari-hesitant guests can be introduced via the Sbagliato (prosecco instead of gin). Expressing the orange oil completely changes the aroma — always do it.",
  },
  {
    name: "Manhattan",
    category: "spirit-forward",
    ingredients: ["50ml rye or bourbon", "25ml sweet vermouth", "2 dashes Angostura bitters"],
    method: "Stir with ice and strain into a chilled glass.",
    glass: "Coupe or Nick & Nora",
    garnish: "Cocktail cherry",
    tip: "Rye produces a drier, spicier Manhattan; bourbon produces a sweeter, rounder one. When a guest orders 'a Manhattan', clarifying their base spirit preference is a worthwhile extra question.",
  },
  {
    name: "Rob Roy",
    category: "spirit-forward",
    ingredients: ["50ml Scotch whisky", "25ml sweet vermouth", "2 dashes Angostura bitters"],
    method: "Stir with ice and strain into a chilled glass.",
    glass: "Coupe",
    garnish: "Cocktail cherry or lemon twist",
    tip: "Essentially a Manhattan made with Scotch. The whisky's character — smoky, peaty or gentle — shapes the entire drink. A useful vehicle for introducing Scotch to a guest who enjoys Bourbon Manhattans.",
  },
  {
    name: "Vesper",
    category: "spirit-forward",
    ingredients: ["45ml gin", "15ml vodka", "10ml Lillet Blanc"],
    method: "Shake hard with ice until very cold and fine strain.",
    glass: "Martini",
    garnish: "Lemon twist",
    tip: "Shaking (unlike a standard Martini) creates more dilution and a colder, slightly cloudier result. A great storytelling drink — the James Bond connection is a reliable conversation opener with guests of all ages.",
  },
  {
    name: "Hanky Panky",
    category: "spirit-forward",
    ingredients: ["45ml gin", "45ml sweet vermouth", "5ml Fernet-Branca"],
    method: "Stir with ice and strain into a chilled glass.",
    glass: "Coupe",
    garnish: "Orange twist, expressed and placed",
    tip: "Created by Ada Coleman at The Savoy in the early 1900s — the first major cocktail attributed to a female head bartender. A small amount of Fernet adds intrigue without dominating. Worth telling the story to curious guests.",
  },
  {
    name: "Americano",
    category: "spirit-forward",
    ingredients: ["35ml Campari", "35ml sweet vermouth", "soda water to top"],
    method: "Build over ice in a glass: Campari first, then vermouth, then soda.",
    glass: "Rocks or highball",
    garnish: "Orange slice",
    tip: "Lower alcohol than most cocktails and approachable for guests wanting something light but sophisticated. The precursor to the Negroni. A useful recommendation for guests who are on a pace or unsure about stronger drinks.",
  },
  {
    name: "Vieux Carre",
    category: "spirit-forward",
    ingredients: ["22ml rye whiskey", "22ml cognac", "22ml sweet vermouth", "7ml Benedictine", "1 dash Peychaud's bitters", "1 dash Angostura bitters"],
    method: "Stir with ice and strain over a large ice block.",
    glass: "Rocks",
    garnish: "Lemon twist and cocktail cherry",
    tip: "A New Orleans classic from the 1930s. The Benedictine adds herbal depth that separates it from a Manhattan. The two-bitters combination is intentional — Peychaud's is floral, Angostura is earthy. Worth knowing when guests are exploring cocktail history.",
  },

  // ─── ANCESTRAL ───────────────────────────────────────────────────────────
  {
    name: "Old Fashioned",
    category: "ancestral",
    ingredients: ["60ml bourbon or rye", "1 sugar cube or 10ml sugar syrup", "2 dashes Angostura bitters", "dash of water"],
    method: "Muddle sugar and bitters in the glass. Add spirit and large ice, stir to chill and combine.",
    glass: "Rocks",
    garnish: "Orange peel, expressed and placed",
    tip: "This format gives guests real influence over their drink — adjust sweetness to preference. Ask about their spirit choice; a Mezcal Old Fashioned is a natural next-level suggestion for guests ready to explore.",
  },
  {
    name: "Sazerac",
    category: "ancestral",
    ingredients: ["60ml rye whiskey", "10ml sugar syrup", "3 dashes Peychaud's bitters", "1 dash Angostura bitters", "absinthe (to rinse the glass)"],
    method: "Rinse a chilled rocks glass with absinthe and discard the excess. Stir remaining ingredients with ice and strain in.",
    glass: "Rocks (served without ice)",
    garnish: "Lemon peel expressed over the glass — do not drop it in",
    tip: "Served neat — no ice. The absinthe rinse perfumes the glass without overpowering. Discarding the lemon peel after expressing the oil is part of the recipe, not laziness. A textbook example of restraint in cocktail making.",
  },
  {
    name: "Toronto",
    category: "ancestral",
    ingredients: ["55ml rye whiskey", "7ml Fernet-Branca", "5ml sugar syrup", "1 dash Angostura bitters"],
    method: "Stir with ice and strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Orange twist",
    tip: "Fernet functions as a complex bittering agent here rather than a modifier — only a small amount is needed. A strong introduction to amaro culture for guests who enjoy classic whiskey cocktails.",
  },
  {
    name: "Oaxacan Old Fashioned",
    category: "ancestral",
    ingredients: ["45ml reposado tequila", "15ml mezcal", "5ml agave nectar", "2 dashes mole bitters"],
    method: "Stir with ice and strain over a large ice cube.",
    glass: "Rocks",
    garnish: "Flamed orange peel",
    tip: "Created by Phil Ward at Death & Co, New York. The mezcal adds smokiness without overwhelming the tequila. A natural recommendation for guests curious about mezcal who find straight mezcal too intense.",
  },
  {
    name: "Improved Whiskey Cocktail",
    category: "ancestral",
    ingredients: ["60ml rye or bourbon", "5ml maraschino liqueur", "5ml absinthe", "10ml sugar syrup", "2 dashes Angostura bitters"],
    method: "Stir with ice and strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lemon twist",
    tip: "A Victorian-era drink predating the term 'Old Fashioned'. The maraschino and absinthe were considered the upgrades at the time. A useful cocktail for explaining to guests how the category has evolved across 150 years.",
  },

  // ─── HIGHBALLS / COLLINS ─────────────────────────────────────────────────
  {
    name: "Gin & Tonic",
    category: "highballs",
    ingredients: ["50ml gin", "150ml premium tonic water"],
    method: "Build in a large copa glass over ice. Add gin, then pour tonic gently down the inside of the glass.",
    glass: "Copa de Balon or highball",
    garnish: "Botanicals that complement the gin — cucumber for London Dry, pink pepper for a spiced gin, grapefruit for a citrus-forward gin",
    tip: "The garnish should complement the gin's botanicals, not default to a lime wedge. Knowing your gin range allows you to make a genuine pairing recommendation. This four-second insight transforms a G&T order into a proper guest experience.",
  },
  {
    name: "Tom Collins",
    category: "highballs",
    ingredients: ["50ml gin", "25ml fresh lemon juice", "15ml sugar syrup", "soda water to top"],
    method: "Shake gin, lemon and sugar with ice. Strain into a Collins glass over fresh ice and top with soda.",
    glass: "Highball (Collins glass)",
    garnish: "Lemon slice, cocktail cherry",
    tip: "Always fresh lemon — never pre-batched. The Collins is a great session cocktail recommendation for guests who want something refreshing over a few hours without getting heavy.",
  },
  {
    name: "Mojito",
    category: "highballs",
    ingredients: ["50ml white rum", "25ml fresh lime juice", "15ml sugar syrup", "8–10 fresh mint leaves", "soda water to top"],
    method: "Press mint very gently with lime juice and sugar in the glass. Add rum and ice, churn lightly, top with soda.",
    glass: "Highball",
    garnish: "Mint sprig, lime wedge",
    tip: "Aggressively muddled mint releases bitter chlorophyll from the stalks. A firm but gentle press is enough. If service is high-volume, batch the lime-sugar-rum base ahead of time and keep fresh mint for per-order assembly.",
  },
  {
    name: "Moscow Mule",
    category: "highballs",
    ingredients: ["50ml vodka", "15ml fresh lime juice", "ginger beer to top"],
    method: "Build over ice in a copper mug. Add vodka and lime, then top with ginger beer.",
    glass: "Copper mug",
    garnish: "Lime wedge, candied ginger (optional)",
    tip: "The copper mug keeps the drink notably colder for longer — it is functional, not just aesthetic. A Kentucky Mule variation (swap vodka for bourbon) is an easy upsell conversation for whiskey-drinking guests.",
  },
  {
    name: "Aperol Spritz",
    category: "highballs",
    ingredients: ["90ml prosecco", "60ml Aperol", "30ml soda water"],
    method: "Build over ice in a large wine glass: prosecco first, then Aperol, then a splash of soda.",
    glass: "Large wine glass",
    garnish: "Orange slice and a green olive",
    tip: "3-2-1 ratio: 3 parts prosecco, 2 parts Aperol, 1 part soda. Many guests ordering this have no idea what Aperol is — 'lightly bitter, slightly sweet Italian aperitivo' is enough to make them feel informed and confident.",
  },
  {
    name: "Dark & Stormy",
    category: "highballs",
    ingredients: ["50ml dark rum", "ginger beer to top", "15ml fresh lime juice"],
    method: "Build over ice. Pour ginger beer first, then lime, then float dark rum on top.",
    glass: "Highball",
    garnish: "Lime wedge",
    tip: "Goslings Black Seal is the original specified rum — the Dark & Stormy name is actually trademarked by them. The rum float reads visually and blends itself as the guest sips. A great drink for telling Caribbean rum stories.",
  },
  {
    name: "Cuba Libre",
    category: "highballs",
    ingredients: ["50ml white or golden rum", "15ml fresh lime juice", "cola to top"],
    method: "Build over ice: lime first, then rum, then cola.",
    glass: "Highball",
    garnish: "Lime wedge",
    tip: "The lime changes the character completely — this is not just rum and cola. When a guest orders 'rum and coke', suggesting the Cuba Libre as the better version takes two seconds and makes a real difference to the drink.",
  },
  {
    name: "Paloma",
    category: "highballs",
    ingredients: ["50ml silver tequila", "15ml fresh lime juice", "grapefruit soda to top"],
    method: "Build over ice. Add lime, then tequila, then grapefruit soda.",
    glass: "Highball",
    garnish: "Grapefruit wedge, optional salt rim",
    tip: "More popular than the Margarita in Mexico. Upgrading from grapefruit soda to fresh grapefruit juice and plain soda is a quality step worth pointing out to interested guests.",
  },
  {
    name: "John Collins",
    category: "highballs",
    ingredients: ["50ml bourbon or blended Scotch", "25ml fresh lemon juice", "15ml sugar syrup", "soda water to top"],
    method: "Shake whiskey, lemon and sugar with ice. Strain into a Collins glass over fresh ice and top with soda.",
    glass: "Highball (Collins glass)",
    garnish: "Lemon slice, cocktail cherry",
    tip: "The whiskey counterpart to the Tom Collins. Bourbon makes it sweeter and rounder; Scotch adds smokiness and bite. A reliable way to guide guests who enjoy whiskey into a more approachable long format.",
  },

  // ─── FIZZ ────────────────────────────────────────────────────────────────
  {
    name: "Gin Fizz",
    category: "fizz",
    ingredients: ["45ml gin", "25ml fresh lemon juice", "15ml sugar syrup", "soda water to top"],
    method: "Shake gin, lemon and sugar hard with ice. Strain into a glass without ice, top with soda.",
    glass: "Highball (no ice)",
    garnish: "Lemon slice",
    tip: "Served without ice — this separates the Fizz from the Collins. Adding ice will kill the carbonation and over-dilute the drink. The soda provides enough chill from the strain. Explain this to guests who ask why there's no ice.",
  },
  {
    name: "Silver Fizz",
    category: "fizz",
    ingredients: ["45ml gin", "25ml fresh lemon juice", "15ml sugar syrup", "20ml egg white", "soda water to top"],
    method: "Dry shake without ice first, then shake with ice. Strain without ice, pour soda slowly down the inside of the glass.",
    glass: "Highball (no ice)",
    garnish: "None — the foam is the garnish",
    tip: "The soda pour angle and speed determines the quality of the foam head. Pour slowly down the glass wall. A Gin Fizz with egg white is technically a Silver Fizz — knowing the distinction demonstrates cocktail literacy.",
  },
  {
    name: "Ramos Gin Fizz",
    category: "fizz",
    ingredients: ["45ml gin", "15ml fresh lemon juice", "15ml fresh lime juice", "15ml sugar syrup", "20ml egg white", "30ml double cream", "3 drops orange flower water", "soda water to top"],
    method: "Shake all ingredients except soda for a minimum of two minutes. Strain into a tall glass without ice and top with soda slowly.",
    glass: "Highball (no ice)",
    garnish: "The foam should rise an inch above the rim — that is the presentation",
    tip: "The most demanding cocktail to make consistently. The extended shake emulsifies cream, egg and citrus into a seamless foam. If executed correctly, the foam rises above the glass rim. Never rush this drink — or don't put it on the menu.",
  },
  {
    name: "Sloe Gin Fizz",
    category: "fizz",
    ingredients: ["45ml sloe gin", "25ml fresh lemon juice", "15ml sugar syrup", "soda water to top"],
    method: "Shake sloe gin, lemon and sugar with ice. Strain without ice, top with soda.",
    glass: "Highball (no ice)",
    garnish: "Lemon slice",
    tip: "Lower ABV and naturally sweet from the sloe gin. An accessible entry point for guests unfamiliar with cocktails. The deep red/pink colour photographs beautifully and makes it easy to sell visually.",
  },
  {
    name: "Buck's Fizz",
    category: "fizz",
    ingredients: ["90ml chilled champagne or prosecco", "45ml fresh orange juice"],
    method: "Pour chilled OJ into a flute, top gently with sparkling wine.",
    glass: "Champagne flute",
    garnish: "Orange twist (optional)",
    tip: "Fresh-squeezed juice only. The ratio matters — too much juice flattens and sweetens. For brunch service batching the OJ and keeping it ice cold is fine, but always open a fresh bottle of sparkling per order. Never use pre-opened fizz.",
  },

  // ─── TIKI & TROPICAL ─────────────────────────────────────────────────────
  {
    name: "Mai Tai",
    category: "tiki",
    ingredients: ["30ml aged rum", "30ml dark Jamaican rum", "15ml orange curacao", "15ml orgeat syrup", "25ml fresh lime juice"],
    method: "Shake with crushed ice and pour unstrained into the glass.",
    glass: "Rocks or tiki mug",
    garnish: "Mint sprig, spent lime shell, cocktail umbrella",
    tip: "Trader Vic's original 1944 recipe used aged Martinique rum. Crushed ice is not optional — it affects dilution and texture. If your venue simplifies to one rum, be able to articulate what that loses in depth.",
  },
  {
    name: "Zombie",
    category: "tiki",
    ingredients: ["30ml white rum", "30ml golden rum", "30ml dark rum", "15ml apricot brandy", "10ml grenadine", "30ml fresh grapefruit juice", "15ml fresh lime juice", "5ml falernum"],
    method: "Shake or blend with crushed ice and pour unstrained.",
    glass: "Zombie glass or large tiki mug",
    garnish: "Mint sprig, lime wheel, cocktail cherry",
    tip: "Donn Beach's original came with a posted two-drink limit per guest because of its strength. If your venue serves this, noting the strength is responsible service — and a story guests genuinely enjoy hearing.",
  },
  {
    name: "Pina Colada",
    category: "tiki",
    ingredients: ["50ml white rum", "50ml coconut cream", "100ml fresh pineapple juice"],
    method: "Blend with crushed ice until smooth, or shake very hard with ice.",
    glass: "Hurricane glass or large tiki cup",
    garnish: "Pineapple wedge, cocktail cherry, wide straw",
    tip: "Coconut cream and coconut milk are very different — cream is thick and rich, milk is thin and watery. A blended Colada should be pourable but not liquid. Wide straws are correct for blended drinks; a standard straw kills the experience.",
  },
  {
    name: "Hurricane",
    category: "tiki",
    ingredients: ["60ml dark rum", "30ml fresh lime juice", "30ml passion fruit syrup", "30ml fresh orange juice", "15ml grenadine"],
    method: "Shake with ice and strain into a glass over crushed ice.",
    glass: "Hurricane glass",
    garnish: "Orange slice, cocktail cherry",
    tip: "Originating at Pat O'Brien's in New Orleans. The tall glass and fruit garnish make this ideal for table service theatre. Grenadine quality makes or breaks this drink — artificial grenadine tastes chemical against fresh juice.",
  },
  {
    name: "Jungle Bird",
    category: "tiki",
    ingredients: ["45ml blackstrap rum", "22ml Campari", "45ml pineapple juice", "15ml fresh lime juice", "15ml sugar syrup"],
    method: "Shake with ice and strain over crushed ice.",
    glass: "Rocks or tiki mug",
    garnish: "Pineapple leaf, dehydrated pineapple slice",
    tip: "One of the rare tiki cocktails featuring Campari — the bitterness plays brilliantly against sweet pineapple. Created at the Kuala Lumpur Hilton in 1978. A natural recommendation for Negroni fans who are open to something tropical.",
  },
  {
    name: "Painkiller",
    category: "tiki",
    ingredients: ["60ml navy-strength rum", "120ml pineapple juice", "30ml orange juice", "30ml coconut cream"],
    method: "Shake vigorously with ice and strain over crushed ice.",
    glass: "Rocks or tiki mug",
    garnish: "Freshly grated nutmeg over the top, orange slice",
    tip: "Born at the Soggy Dollar Bar in the British Virgin Islands. Navy-strength rum (57% ABV) is part of the original recipe — worth communicating to guests since it significantly affects the drink's impact on a warm day.",
  },
  {
    name: "Singapore Sling",
    category: "tiki",
    ingredients: ["30ml gin", "15ml cherry liqueur", "7ml Cointreau", "7ml Benedictine", "120ml pineapple juice", "15ml fresh lime juice", "10ml grenadine", "1 dash Angostura bitters"],
    method: "Shake all ingredients with ice and strain into a glass over fresh ice.",
    glass: "Hurricane or sling glass",
    garnish: "Pineapple slice, cocktail cherry",
    tip: "Created at Raffles Hotel Singapore around 1915. The recipe has been widely adapted over the decades. Even knowing the rough history makes this far more interesting to serve — and to guests who are paying heritage hotel prices for a cocktail experience.",
  },

  // ─── DUOS & TRIOS ────────────────────────────────────────────────────────
  {
    name: "Black Russian",
    category: "duos-trios",
    ingredients: ["50ml vodka", "25ml coffee liqueur"],
    method: "Build over ice in a rocks glass. Spirit first, liqueur second.",
    glass: "Rocks",
    garnish: "3 coffee beans (optional)",
    tip: "One of the simplest cocktails in any repertoire — which means ingredient quality is everything. If a guest orders this, it is a natural opening to ask about their love of coffee and guide them toward an Espresso Martini for something more elaborate.",
  },
  {
    name: "White Russian",
    category: "duos-trios",
    ingredients: ["50ml vodka", "25ml coffee liqueur", "30ml double cream (floated)"],
    method: "Build vodka and coffee liqueur over ice. Gently float cream over the back of a bar spoon.",
    glass: "Rocks",
    garnish: "None — the cream float is the visual",
    tip: "Do not stir the cream in. Guests mix it themselves as they drink, receiving a changing ratio from first sip to last. Made famous by The Big Lebowski. If guests bring up the film reference, lean into it — it is part of the drink's identity.",
  },
  {
    name: "Godfather",
    category: "duos-trios",
    ingredients: ["50ml Scotch whisky", "25ml amaretto"],
    method: "Build over a large ice cube. Stir gently to combine.",
    glass: "Rocks",
    garnish: "Orange peel (optional)",
    tip: "The amaretto softens the Scotch and introduces almond sweetness — a reliable entry point for guests curious about Scotch but finding it too aggressive neat. The film connection makes it an easy recommendation at a premium venue.",
  },
  {
    name: "Rusty Nail",
    category: "duos-trios",
    ingredients: ["50ml Scotch whisky", "25ml Drambuie"],
    method: "Build over a large ice cube. Add Drambuie last.",
    glass: "Rocks",
    garnish: "Lemon twist",
    tip: "Drambuie is a Scotch-based liqueur with honey, heather and highland herbs — it enhances rather than masks the whisky. A sophisticated after-dinner drink. Worth noting the liqueur's Scottish origin when recommending it to Scotch enthusiasts.",
  },
  {
    name: "Stinger",
    category: "duos-trios",
    ingredients: ["60ml cognac", "20ml white creme de menthe"],
    method: "Shake with ice and strain into a chilled glass.",
    glass: "Coupe",
    garnish: "Mint leaf",
    tip: "A classic pre-war digestif. The white creme de menthe provides a cooling sensation that makes cognac feel surprisingly refreshing. Served straight up. A strong after-dinner recommendation for guests who enjoy brandy.",
  },
  {
    name: "B&B",
    category: "duos-trios",
    ingredients: ["35ml cognac or brandy", "35ml Benedictine"],
    method: "Build in a brandy snifter or rocks glass. Can be served neat or over ice.",
    glass: "Brandy snifter or rocks",
    garnish: "None",
    tip: "Benedictine's herbal complexity does a great deal of work here — warm, slightly honeyed, with herbal aromatic spice. If guests ask what Benedictine tastes like, describe it as 'honeyed herbs with warmth'. One of the oldest liqueurs still in commercial production.",
  },

  // ─── CHAMPAGNE & SPARKLING ────────────────────────────────────────────────
  {
    name: "French 75",
    category: "sparkling",
    ingredients: ["30ml gin", "15ml fresh lemon juice", "10ml sugar syrup", "60ml champagne to top"],
    method: "Shake gin, lemon and sugar with ice. Fine strain into a chilled flute and top with champagne.",
    glass: "Champagne flute",
    garnish: "Lemon twist",
    tip: "Named after the French 75mm artillery cannon — it hits with similar force. The classic base is gin; cognac is the New Orleans variation. Always use quality sparkling wine. A Champagne Cocktail that rewards good ingredients with a noticeably better result.",
  },
  {
    name: "Mimosa",
    category: "sparkling",
    ingredients: ["90ml chilled champagne or prosecco", "45ml fresh orange juice"],
    method: "Pour chilled orange juice into a flute first. Top gently with sparkling wine.",
    glass: "Champagne flute",
    garnish: "Orange twist (optional)",
    tip: "Fresh-squeezed juice only — carton OJ loses brightness quickly. Serve immediately after topping to preserve carbonation. For brunch service, batch the juice cold in advance but always open sparkling per order.",
  },
  {
    name: "Bellini",
    category: "sparkling",
    ingredients: ["90ml prosecco", "45ml white peach puree"],
    method: "Pour peach puree into a chilled flute. Top gently with prosecco.",
    glass: "Champagne flute",
    garnish: "None",
    tip: "Created at Harry's Bar in Venice in the 1940s. White peach puree in season is ideal, but a high-quality commercial puree is accepted practice. If you make it in-house, say so — that fact alone has significant menu value.",
  },
  {
    name: "Kir Royale",
    category: "sparkling",
    ingredients: ["10ml creme de cassis", "120ml champagne or quality sparkling wine"],
    method: "Pour cassis into a chilled flute. Top gently with champagne.",
    glass: "Champagne flute",
    garnish: "None",
    tip: "Cassis settles — advise guests to let it blend naturally as they drink rather than stir it. The non-royal version 'Kir' uses still white wine. A very small amount of cassis delivers a lot; resist the urge to free-pour it.",
  },
  {
    name: "Champagne Cocktail",
    category: "sparkling",
    ingredients: ["1 white sugar cube", "3 dashes Angostura bitters", "15ml cognac", "champagne to top"],
    method: "Soak sugar cube in Angostura, drop into a flute. Add cognac, then top slowly with champagne.",
    glass: "Champagne flute",
    garnish: "Lemon twist, orange peel",
    tip: "The soaked sugar cube slowly dissolves, creating a continuous stream of bubbles rising through the glass — half garnish, half spectacle. Preparing the bitters-soaked cubes in advance speeds up service without compromising presentation.",
  },
  {
    name: "Negroni Sbagliato",
    category: "sparkling",
    ingredients: ["30ml sweet vermouth", "30ml Campari", "30ml prosecco"],
    method: "Build over ice: vermouth, then Campari, then prosecco.",
    glass: "Rocks",
    garnish: "Orange slice",
    tip: "Italian for 'wrong Negroni' — a bartender reaching for prosecco instead of gin by accident. Lower alcohol and lighter than a classic Negroni. Became a mainstream order after a widely-shared celebrity interview. Know it — guests ask for it by name.",
  },

  // ─── HOT COCKTAILS ───────────────────────────────────────────────────────
  {
    name: "Hot Toddy",
    category: "hot",
    ingredients: ["50ml Scotch or Irish whiskey", "25ml fresh lemon juice", "15ml honey syrup", "150ml near-boiling water"],
    method: "Warm the glass first. Combine honey and lemon in the glass, add whiskey, top with hot water.",
    glass: "Warmed mug or heat-proof glass",
    garnish: "Lemon slice studded with cloves, cinnamon stick",
    tip: "Warming the glass is not optional — a cold glass drops the drink temperature instantly. Dissolving the honey in lemon juice before adding spirit ensures even mixing. Guests ordering this want to feel looked after; service manner matters here.",
  },
  {
    name: "Irish Coffee",
    category: "hot",
    ingredients: ["40ml Irish whiskey", "150ml hot filter coffee", "15ml brown sugar syrup", "30ml double cream (lightly whipped)"],
    method: "Warm the glass. Add whiskey and sugar syrup, then coffee. Float lightly whipped cream gently over the back of a spoon.",
    glass: "Footed heat-proof glass (Irish coffee glass)",
    garnish: "None — the cream layer is the garnish",
    tip: "The cream should float, not sink. Whip it to just past liquid — it needs to hold its shape for a moment but not be stiff. Guests drink through the cream; a stiff or broken cream head ruins the experience. A reliable test of patience and technique.",
  },
  {
    name: "Hot Buttered Rum",
    category: "hot",
    ingredients: ["50ml dark rum", "15ml honey", "small pat of unsalted butter", "pinch of cinnamon, nutmeg and cloves", "150ml hot water"],
    method: "Mix butter, honey and spices directly in a warmed mug. Add rum and hot water, stir until butter melts.",
    glass: "Mug",
    garnish: "Cinnamon stick, grated nutmeg",
    tip: "Pre-mixing a batter of butter, honey and spices in advance is standard service practice — it speeds up output and maintains consistency. The butter adds a richness distinct from cream-based drinks. A genuine cold-weather comfort drink.",
  },
  {
    name: "Cafe Royale",
    category: "hot",
    ingredients: ["150ml strong filter coffee", "30ml cognac", "10ml sugar syrup"],
    method: "Combine in a warmed glass. Optionally, pour a spoonful of cognac over the back of a spoon and flame it briefly before allowing it to burn out.",
    glass: "Heat-proof glass or small mug",
    garnish: "Flamed cognac (optional), brown sugar crystals",
    tip: "The flaming is theatre — the alcohol burns off in seconds. When executed tableside it is a remarkable piece of service craft. Practice exclusively at quiet times, not mid-service. The safety of nearest guests always comes before the spectacle.",
  },
  {
    name: "Mulled Wine",
    category: "hot",
    ingredients: ["1 bottle red wine", "2 cinnamon sticks", "4 cloves", "2 star anise", "1 orange sliced into rounds", "50ml brandy", "sugar to taste"],
    method: "Heat all ingredients very gently in a pot. Do not boil. Ladle into heat-proof glasses.",
    glass: "Mug or heat-proof glass",
    garnish: "Cinnamon stick, orange slice",
    tip: "Boiling drives off the alcohol and flattens the spice aroma. Hold at around 70°C for service. Taste and adjust sweetness before service begins — wine varies. Adding brandy after heating maintains its depth. Batch in advance; this improves with resting time.",
  },

  // ─── FLIPS & NOGS ────────────────────────────────────────────────────────
  {
    name: "Classic Eggnog",
    category: "flips-nogs",
    ingredients: ["45ml bourbon or dark rum", "15ml cognac", "1 whole egg", "30ml sugar syrup", "60ml whole milk", "30ml double cream"],
    method: "Shake all ingredients without ice first, then with ice. Strain into a chilled glass.",
    glass: "Rocks or punch cup",
    garnish: "Freshly grated nutmeg — applied generously",
    tip: "The double shake emulsifies the egg fully. Nutmeg is essential and cuts through the richness. Commonly seasonal, but worth mastering for winter menus. For large-volume events, a spirit-and-egg base aged overnight in the fridge deepens the flavour considerably.",
  },
  {
    name: "Brandy Alexander",
    category: "flips-nogs",
    ingredients: ["30ml cognac or brandy", "30ml dark creme de cacao", "30ml double cream"],
    method: "Shake all ingredients hard with ice and double strain into a chilled glass.",
    glass: "Coupe",
    garnish: "Freshly grated nutmeg",
    tip: "A post-dinner dessert cocktail. The creme de cacao gives chocolate sweetness without heaviness. A reliable recommendation for guests who want 'something sweet but not too rich'. The nutmeg aroma is the defining first impression — be generous with it.",
  },
  {
    name: "Porto Flip",
    category: "flips-nogs",
    ingredients: ["45ml ruby port", "15ml cognac", "1 egg yolk", "10ml sugar syrup"],
    method: "Shake very hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Freshly grated nutmeg",
    tip: "The egg yolk provides richness without the full body of a whole egg. Quality ruby port is naturally sweet, so the sugar syrup here is minimal. A sophisticated and underserved after-dinner choice worth championing on any menu.",
  },
  {
    name: "Bourbon Flip",
    category: "flips-nogs",
    ingredients: ["60ml bourbon", "1 whole egg", "15ml sugar syrup"],
    method: "Shake vigorously without ice first, then with ice. Double strain into a coupe.",
    glass: "Coupe",
    garnish: "Freshly grated nutmeg",
    tip: "A whole egg adds body and a subtle savoury depth that separates a Flip from a Sour. Double straining removes the chalaza. The shake must be sustained and committed — under-shaking leaves the drink textually inconsistent.",
  },
  {
    name: "Sherry Flip",
    category: "flips-nogs",
    ingredients: ["60ml Amontillado sherry", "1 whole egg", "10ml sugar syrup"],
    method: "Shake hard without ice, then with ice. Double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Freshly grated nutmeg, a small sherry biscuit on the side (optional)",
    tip: "Amontillado sherry brings a dry, nutty character that pairs beautifully with egg. Lower in alcohol but full of complexity. Sherry is consistently underrepresented in bar culture — this is a strong and elegant vehicle for introducing it after a meal.",
  },
];
