export type Category =
  | "sours"
  | "spirit-forward"
  | "ancestral"
  | "highballs"
  | "fizz"
  | "tiki"
  | "duos-trios"
  | "sparkling"
  | "hot"
  | "flips-nogs";

export type Cocktail = {
  name: string;
  category: Category;
  ingredients: string[];
  method: string;
  glass: string;
  garnish: string;
  tip: string;
};

export const CATEGORIES: Record<Category, { label: string; description: string; color: string }> = {
  sours: {
    label: "Sours",
    description: "The backbone of modern cocktail making. Spirit + fresh citrus + sweetener in balance. Master the ratio and you can build almost any sour on the fly.",
    color: "#f5a623",
  },
  "spirit-forward": {
    label: "Spirit-Forward",
    description: "The spirit is the star. Blended with vermouth or fortified wine and always stirred — never shaken — to preserve a silky, clear texture.",
    color: "#4a90d9",
  },
  ancestral: {
    label: "Ancestral / Old Fashioned",
    description: "One of the oldest formats in cocktail history. Spirit, sugar, bitters and dilution. Nothing extra. Precision and restraint define this style.",
    color: "#8b5e3c",
  },
  highballs: {
    label: "Highballs & Collins",
    description: "Spirit over ice in a tall glass, topped with a carbonated mixer. Refreshing, versatile and among the most-ordered drinks in any venue.",
    color: "#5cb85c",
  },
  fizz: {
    label: "Fizz",
    description: "A sour extended with soda water, served without ice. Silver Fizz adds egg white for a creamy foam top. Technique-driven and highly satisfying to execute well.",
    color: "#9b59b6",
  },
  tiki: {
    label: "Tiki & Tropical",
    description: "Bold, layered and theatrical. Typically rum-based with fruit juices, spices and syrups. Often served in oversized or decorative glassware.",
    color: "#e74c3c",
  },
  "duos-trios": {
    label: "Duos & Trios",
    description: "A Duo is spirit plus liqueur. Add cream and it becomes a Trio. Simple builds where the quality and ratio of each ingredient determines everything.",
    color: "#1abc9c",
  },
  sparkling: {
    label: "Champagne & Sparkling",
    description: "Champagne or sparkling wine as a key component. Light, celebratory and versatile. Technique is gentle — always add sparkling last to preserve the bubbles.",
    color: "#f39c12",
  },
  hot: {
    label: "Hot Cocktails",
    description: "Served warm, these drinks provide comfort and richness. Temperature management and glassware preparation are the most important techniques.",
    color: "#e67e22",
  },
  "flips-nogs": {
    label: "Flips & Nogs",
    description: "Rich, indulgent drinks built around whole eggs or egg components, dairy and sweetener. A vigorous shake emulsifies everything into something deeply satisfying.",
    color: "#7f8c8d",
  },
};

export const COCKTAILS: Cocktail[] = [
  // ─── SOURS ───────────────────────────────────────────────────────────────
  {
    name: "Classic Daiquiri",
    category: "sours",
    ingredients: ["60ml white rum", "25ml fresh lime juice", "15ml sugar syrup"],
    method: "Shake hard with ice and double strain into a chilled glass.",
    glass: "Coupe",
    garnish: "Lime wheel on the rim",
    tip: "Fresh lime only — never bottled. The 2:1:¾ ratio is your baseline; adjust sweetness daily based on the lime's acidity. Bundaberg Rum is a natural Australian choice here.",
  },
  {
    name: "Margarita",
    category: "sours",
    ingredients: ["50ml silver tequila", "25ml fresh lime juice", "20ml triple sec"],
    method: "Shake with ice and strain into a chilled glass with a salt rim.",
    glass: "Coupe or Margarita glass",
    garnish: "Salt rim (half-salted), lime wedge",
    tip: "Always ask before salting — never assume. Half-salt the rim so guests choose with every sip. Spicy Margarita with jalapeño is an easy upsell conversation.",
  },
  {
    name: "Whiskey Sour",
    category: "sours",
    ingredients: ["50ml bourbon", "25ml fresh lemon juice", "15ml sugar syrup", "20ml egg white (optional)"],
    method: "If using egg white, dry shake first without ice, then shake again with ice. Double strain into a coupe.",
    glass: "Coupe",
    garnish: "Lemon wheel and two dashes of Angostura bitters on the foam",
    tip: "The egg white creates a silky mouthfeel and beautiful presentation. Practice the dry shake technique — it's essential for consistent foam. Starward Whisky is an outstanding Australian alternative to bourbon.",
  },
  {
    name: "Pisco Sour",
    category: "sours",
    ingredients: ["60ml Pisco", "25ml fresh lime juice", "20ml sugar syrup", "20ml egg white"],
    method: "Dry shake egg white first, then add ice and remaining ingredients. Shake hard and double strain.",
    glass: "Coupe",
    garnish: "Three dashes of Angostura bitters on foam",
    tip: "This South American classic showcases how different spirits tell different stories. The acidity of fresh lime is critical — adjust daily. Teaching this drink trains bartenders to understand the science of sours.",
  },
  {
    name: "Sazerac",
    category: "ancestral",
    ingredients: ["60ml rye whiskey", "¼ tsp Peychaud's bitters", "¼ tsp Absinthe rinse"],
    method: "Rinse a chilled rocks glass with absinthe, discard excess. Stir whiskey and bitters with ice, strain into glass.",
    glass: "Rocks (Old Fashioned)",
    garnish: "Lemon peel expressed over the surface",
    tip: "The 1823 New Orleans classic. This drink is pure spirit, minimal dilution, and technique-focused. It's the foundation for understanding spirit-forward cocktails. Try using Starward Whisky for an Australian spin.",
  },
  {
    name: "Mojito",
    category: "highballs",
    ingredients: ["50ml white rum", "12 fresh mint leaves", "15ml fresh lime juice", "15ml sugar syrup", "Top with soda water"],
    method: "Gently press mint to release oils (don't destroy leaves). Add rum, lime, syrup, and ice. Top with soda and stir gently.",
    glass: "Highball",
    garnish: "Mint sprig and lime wheel",
    tip: "Gentle pressing only — bruised mint turns bitter. Keep ingredients cold and fresh. This is a venue staple worldwide. Bundaberg Rum pairs beautifully here.",
  },
  {
    name: "Aperol Spritz",
    category: "sparkling",
    ingredients: ["60ml Prosecco", "40ml Aperol", "20ml soda water"],
    method: "Build in order over ice in a wine glass. Stir gently.",
    glass: "Wine glass or large coupe",
    garnish: "Orange slice",
    tip: "The simplicity is the point. This is one of the world's fastest-growing cocktails and a strong house standard. Always add Prosecco first, soda last. Perfect for Australian summer venues.",
  },
  {
    name: "Negroni",
    category: "spirit-forward",
    ingredients: ["30ml gin", "30ml Campari", "30ml sweet vermouth"],
    method: "Stir with ice for 10 seconds and strain into a rocks glass with a large ice cube.",
    glass: "Rocks (Old Fashioned)",
    garnish: "Orange peel expressed over the surface",
    tip: "The 1:1:1 ratio is immutable. Use Four Pillars Gin for an outstanding Australian take on this classic. The bitter-sweet balance is a teaching moment for understanding how spirits interact.",
  },
  {
    name: "Four Pillars Gin & Tonic",
    category: "highballs",
    ingredients: ["50ml Four Pillars Gin", "150ml premium tonic water", "Ice"],
    method: "Build in order over ice in a balloon glass. Stir gently.",
    glass: "Balloon glass",
    garnish: "Lemon wheel and native finger lime if available",
    tip: "Four Pillars is one of Australia's finest gins. The botanicals shine when paired with quality tonic. This is a must-know for Australian venues. Always use fresh ice.",
  },
  {
    name: "Espresso Martini",
    category: "duos-trios",
    ingredients: ["50ml vodka", "25ml Kahlúa (or Mr Black)", "30ml fresh espresso", "15ml sugar syrup"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Three coffee beans floating on the foam",
    tip: "The shake creates a beautiful crema foam. Use Mr Black, an Australian coffee liqueur, for authenticity. Timing matters — add hot espresso to cold ingredients just before serving for the signature foam.",
  },
  {
    name: "Archie Rose Vodka Soda",
    category: "highballs",
    ingredients: ["50ml Archie Rose Vodka", "120ml premium soda water"],
    method: "Build in order over ice. Stir gently.",
    glass: "Highball",
    garnish: "Lime wheel",
    tip: "Archie Rose is a Sydney-based distillery producing world-class spirits. This simple build showcases the vodka's purity. A great entry point for customers exploring Australian craft spirits.",
  },
  {
    name: "Lime & Coriander Sour",
    category: "sours",
    ingredients: ["50ml gin", "25ml fresh lime juice", "15ml sugar syrup", "3 fresh coriander leaves"],
    method: "Gently press coriander to release oils. Shake with ice and double strain.",
    glass: "Coupe",
    garnish: "Coriander sprig",
    tip: "Modern Australian bars are experimenting with native and aromatic botanicals. This drink teaches flexibility — the principle applies to any herb-infused sour. Use Four Pillars for a complete Australian experience.",
  },
  {
    name: "Old Fashioned",
    category: "ancestral",
    ingredients: ["60ml bourbon", "1 sugar cube", "2 dashes Angostura bitters", "Orange peel oil"],
    method: "Dissolve sugar cube with bitters in a rocks glass. Add bourbon and large ice cube. Stir gently.",
    glass: "Rocks (Old Fashioned)",
    garnish: "Orange peel expressed, lemon twist optional",
    tip: "The grandfather of cocktails. Precision and restraint. Starward Whisky brings an Australian terroir to this timeless drink. Teach bartenders why dilution matters by showing the difference between stirring 10 vs 15 seconds.",
  },
  {
    name: "Last Word",
    category: "sours",
    ingredients: ["30ml gin", "30ml green Chartreuse", "30ml fresh lime juice", "30ml maraschino liqueur"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lime wheel",
    tip: "Equal parts, equal balance. This 1920s cocktail is a teaching masterclass in how to build a complex sour. Four Pillars Gin gives this drink an Australian identity.",
  },
  {
    name: "Gin Fizz",
    category: "fizz",
    ingredients: ["50ml gin", "25ml fresh lemon juice", "15ml sugar syrup", "Top with soda water"],
    method: "Shake gin, lemon, and syrup with ice. Strain into a glass without ice. Top with soda and stir gently.",
    glass: "Highball",
    garnish: "Lemon wheel",
    tip: "The Fizz format transforms a sour by removing ice and adding soda. Teaches the spectrum of sour variations. Use Four Pillars Gin for a standout Australian version.",
  },
  {
    name: "Mai Tai",
    category: "tiki",
    ingredients: ["40ml aged rum", "15ml orange Curaçao", "25ml fresh lime juice", "10ml sugar syrup", "2 dashes Angostura bitters"],
    method: "Shake hard with crushed ice. Strain into a rocks glass filled with fresh crushed ice.",
    glass: "Rocks or tiki mug",
    garnish: "Lime wheel and mint sprig",
    tip: "The most imitated drink in the world. Complexity comes from layering flavours carefully. Rum sourcing is critical — explore Australian rum alternatives like Bundaberg for venue differentiation.",
  },
  {
    name: "Dark & Stormy",
    category: "highballs",
    ingredients: ["50ml dark rum", "120ml spicy ginger beer", "15ml fresh lime juice"],
    method: "Build in a rocks glass with ice. Stir gently.",
    glass: "Rocks",
    garnish: "Lime wheel",
    tip: "Ginger beer is essential — never use ginger ale. This drink has protected terms in Bermuda. Bundaberg Rum is ideal here, though any quality dark rum works. Great teaching drink for understanding spirit-mixer ratios.",
  },
  {
    name: "Pina Colada",
    category: "tiki",
    ingredients: ["50ml white rum", "90ml pineapple juice", "60ml coconut cream"],
    method: "Blend with crushed ice until smooth. Pour into a chilled glass.",
    glass: "Tiki mug or hurricane glass",
    garnish: "Pineapple wedge and cherry",
    tip: "A 1950s tropical classic. Blending technique matters — consistent texture is key. This is a high-profit, high-volume drink. Teach bartenders to master blending consistency.",
  },
  {
    name: "Cosmopolitan",
    category: "sours",
    ingredients: ["40ml vodka", "15ml Cointreau", "25ml fresh cranberry juice", "10ml fresh lime juice"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lime wheel on the rim",
    tip: "Citrus balance is critical — adjust lime juice based on juice acidity. This 1980s classic defined a generation of bartending. Use Archie Rose Vodka for an Australian touch.",
  },
  {
    name: "Sidecar",
    category: "sours",
    ingredients: ["50ml Cognac", "20ml Cointreau", "25ml fresh lemon juice"],
    method: "Shake hard with ice and double strain into a chilled coupe, optionally sugar-rimmed.",
    glass: "Coupe",
    garnish: "Orange peel or lemon twist",
    tip: "A pre-Prohibition classic. Cognac sourcing sets quality apart. The 2:1:1 ratio teaches bartenders how spirit richness changes sweet/sour balance. Consider alternatives to Cognac for cost flexibility.",
  },
  {
    name: "Manhattan",
    category: "spirit-forward",
    ingredients: ["60ml rye whiskey", "30ml sweet vermouth", "2 dashes Angostura bitters"],
    method: "Stir with ice for 10 seconds and strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Cherry",
    tip: "A 1870s New York classic. Proper stirring technique is essential — teaches bartenders why dilution and temperature matter. Starward Whisky brings an Australian character to this timeless drink.",
  },
  {
    name: "Dry Martini",
    category: "spirit-forward",
    ingredients: ["60ml gin", "10ml dry vermouth", "2 dashes orange bitters (optional)"],
    method: "Stir with ice for 10 seconds and strain into a chilled coupe.",
    glass: "Coupe or martini glass",
    garnish: "Lemon twist or olive",
    tip: "Simplicity is deception. This drink demands perfect technique and premium ingredients. Four Pillars Gin makes this Australian. Vermouth quality is underestimated — invest in good vermouth.",
  },
  {
    name: "Margarita (Modern Savory)",
    category: "sours",
    ingredients: ["50ml tequila", "25ml fresh lime juice", "15ml agave syrup", "1 pinch sea salt", "Optional: few drops chilli oil"],
    method: "Shake with ice and strain. Add salt directly to glass or rim.",
    glass: "Coupe",
    garnish: "Lime wheel, chilli flake rim",
    tip: "Australian bars are embracing savory cocktails. Chilli oil adds depth without overpowering. This shows how classic drinks adapt to modern palates — encourage experimentation.",
  },
  {
    name: "Starward Whisky Smash",
    category: "sours",
    ingredients: ["50ml Starward Whisky", "25ml fresh lemon juice", "15ml sugar syrup", "6 mint leaves"],
    method: "Gently press mint. Shake with ice and double strain.",
    glass: "Coupe",
    garnish: "Mint sprig",
    tip: "Starward Whisky is Melbourne-distilled and deserves celebration. This drink showcases the distillery's fruit-forward character. A perfect bridge for introducing customers to Australian craft whisky.",
  },
  {
    name: "Bundaberg Old Fashioned",
    category: "ancestral",
    ingredients: ["50ml Bundaberg Rum", "1 sugar cube", "2 dashes Angostura bitters", "Orange peel oil"],
    method: "Dissolve sugar with bitters. Add rum and large ice cube. Stir gently.",
    glass: "Rocks",
    garnish: "Orange peel expressed",
    tip: "Bundaberg Rum, established 1888, is Queensland heritage. The molasses character brings richness to this format. Teaches bartenders how spirit selection changes the same template cocktail.",
  },
  {
    name: "Four Pillars Pink Gin Fizz",
    category: "fizz",
    ingredients: ["50ml Four Pillars Pink Gin", "25ml fresh lemon juice", "15ml sugar syrup", "Top with soda water"],
    method: "Shake gin, lemon, syrup with ice. Strain without ice into a glass. Top with soda.",
    glass: "Highball",
    garnish: "Lemon wheel and berries",
    tip: "Four Pillars Pink Gin uses Australian berries. This showcases local botanicals beautifully. The Fizz format is versatile — teach bartenders to apply it to any sour.",
  },
  {
    name: "Passionfruit Rum Punch",
    category: "tiki",
    ingredients: ["40ml white rum", "40ml dark rum", "25ml fresh passionfruit pulp", "15ml sugar syrup", "20ml fresh lime juice"],
    method: "Shake hard with ice and double strain over fresh ice.",
    glass: "Rocks or tiki mug",
    garnish: "Passionfruit flower and lime wheel",
    tip: "Passionfruit is quintessentially Australian. This punch teaches how tropical fruits elevate classic formats. Bundaberg Rum is perfect here. Great for group service.",
  },
  {
    name: "Lemon Drop Martini",
    category: "duos-trios",
    ingredients: ["40ml vodka", "20ml Cointreau", "15ml fresh lemon juice", "5ml sugar syrup"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lemon twist on rim",
    tip: "A modern classic born in 1970s Los Angeles. Citrus sharpness is essential — fresh lemon juice only. Use Archie Rose Vodka for an Australian connection.",
  },
  {
    name: "Negroni Sbagliato",
    category: "sparkling",
    ingredients: ["30ml Campari", "30ml sweet vermouth", "60ml Prosecco"],
    method: "Build in a wine glass over ice. Stir gently.",
    glass: "Wine glass",
    garnish: "Orange peel",
    tip: "The 'wrong Negroni' — born when a bartender accidentally grabbed Prosecco instead of gin. The sparkling version is lighter and perfect for afternoon service. Teaches improvisation.",
  },
  {
    name: "Jungle Bird",
    category: "tiki",
    ingredients: ["45ml dark rum", "30ml Campari", "40ml pineapple juice", "15ml fresh lime juice"],
    method: "Shake hard with ice and double strain over fresh crushed ice.",
    glass: "Rocks or tiki mug",
    garnish: "Pineapple leaf and lime wheel",
    tip: "A 1960s Tiki classic from Malaysia. The Campari-pineapple combination is unexpected but balanced. Teaches bartenders to think beyond traditional ratios. Use Bundaberg Rum.",
  },
  {
    name: "Aviation",
    category: "sours",
    ingredients: ["50ml gin", "20ml maraschino liqueur", "15ml fresh lemon juice"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Cherry (maraschino optional — fresh is better)",
    tip: "A pre-Prohibition sour. The maraschino is subtle — don't overdo it. Four Pillars Gin makes this distinctly Australian. Teaches that less is sometimes more.",
  },
  {
    name: "Sazerac Archie Rose",
    category: "ancestral",
    ingredients: ["60ml Archie Rose Vodka", "¼ tsp Peychaud's bitters", "¼ tsp Absinthe rinse", "Ice"],
    method: "Rinse a chilled rocks glass with absinthe. Stir vodka and bitters. Strain into glass.",
    glass: "Rocks",
    garnish: "Lemon peel expressed",
    tip: "A Sydney twist on the New Orleans classic. Archie Rose Vodka is smooth and versatile. This teaches how spirit choice can transform a template.",
  },
  {
    name: "Daiquiri Variation: Starward Spice",
    category: "sours",
    ingredients: ["60ml Starward Whisky", "25ml fresh lime juice", "15ml spiced honey syrup"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lime wheel",
    tip: "Australian whisky in a classic template. The spiced honey adds depth. Teaches bartenders that spirit swaps can create new signatures from existing formats.",
  },
  {
    name: "Aperitif Hour: Campari Soda",
    category: "highballs",
    ingredients: ["50ml Campari", "100ml soda water"],
    method: "Build in a rocks glass over ice. Stir gently.",
    glass: "Rocks",
    garnish: "Orange slice",
    tip: "The quintessential Italian aperitif. Simple, refreshing, and a gateway to bitter appreciation. This is a strong afternoon/pre-dinner drink. Teaches how bitters are an acquired taste.",
  },
  {
    name: "Corpse Reviver #2",
    category: "sours",
    ingredients: ["30ml gin", "30ml Cointreau", "30ml Lillet Blanc", "30ml fresh lemon juice", "1 dash absinthe"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lemon twist",
    tip: "A legendary 1920s hangover cure. Equal parts teaching the spectrum of spirits. The absinthe rinse is subtle but essential. Uses multiple modifiers — teaches balance.",
  },
  {
    name: "Rum Old Fashioned",
    category: "ancestral",
    ingredients: ["60ml aged rum", "1 sugar cube", "2 dashes Angostura bitters"],
    method: "Dissolve sugar with bitters. Add rum and large ice cube. Stir gently.",
    glass: "Rocks",
    garnish: "Orange peel",
    tip: "Aged rum brings vanilla and oak richness to this format. Bundaberg Rum's molasses character shines here. Teaches how spirit selection dictates the tasting experience.",
  },
  {
    name: "Paloma",
    category: "highballs",
    ingredients: ["50ml tequila", "90ml grapefruit juice", "20ml fresh lime juice", "10ml sugar syrup"],
    method: "Shake with ice and strain into a salt-rimmed rocks glass.",
    glass: "Rocks or highball",
    garnish: "Grapefruit wedge, salt rim",
    tip: "Mexico's answer to the Margarita. Fresh grapefruit juice is non-negotiable. The salt rim enhances the citrus-bitter balance. Great for teaching juice quality.",
  },
  {
    name: "Shandy (Beer Cocktail)",
    category: "highballs",
    ingredients: ["250ml pale ale", "100ml ginger beer", "Squeeze of fresh lemon"],
    method: "Pour beer into a glass, top with ginger beer. Stir gently. Add lemon juice.",
    glass: "Pint glass",
    garnish: "Lemon wheel",
    tip: "A classic Australian summer drink. Light, refreshing, and session-friendly. Teaches bartenders to work with beer as a cocktail ingredient. Perfect for day venues.",
  },
  {
    name: "Hot Toddy",
    category: "hot",
    ingredients: ["50ml bourbon", "150ml hot water", "15ml honey", "10ml fresh lemon juice", "Cinnamon stick"],
    method: "Dissolve honey in hot water. Add bourbon and lemon juice. Stir gently.",
    glass: "Heat-safe glass or mug",
    garnish: "Cinnamon stick and lemon wheel",
    tip: "A classic winter warmer. Temperature management is key — never boil. Starward Whisky brings Australian character. Teaches bartenders comfort-drink culture.",
  },
  {
    name: "Irish Coffee",
    category: "hot",
    ingredients: ["40ml Irish whiskey", "120ml hot strong coffee", "10ml brown sugar", "30ml heavy cream"],
    method: "Dissolve sugar in hot coffee. Add whiskey. Float cream over the back of a hot spoon.",
    glass: "Irish coffee glass or heat-safe mug",
    garnish: "Whipped cream",
    tip: "The iconic hot cocktail. Cream floating is an art — practice the spoon technique. Teaches bartenders that presentation matters as much as flavour.",
  },
  {
    name: "Eggnog",
    category: "flips-nogs",
    ingredients: ["40ml aged rum", "30ml bourbon", "20ml whole egg", "40ml crème fraîche", "10ml sugar syrup", "Nutmeg to finish"],
    method: "Dry shake egg first. Add remaining ingredients and shake hard with ice. Strain into a rocks glass.",
    glass: "Rocks",
    garnish: "Freshly grated nutmeg",
    tip: "A festive classic. Whole egg provides richness. This teaches egg white/yolk usage. Seasonal sales potential. Can be prepared as batches in advance.",
  },
  {
    name: "Brandy Alexander",
    category: "duos-trios",
    ingredients: ["30ml Cognac", "30ml crème de cacao", "30ml heavy cream"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Freshly grated nutmeg",
    tip: "A 1920s classic dessert drink. Cream quality is critical. This teaches the Trio format. Rich, indulgent, perfect for after-dinner service.",
  },
  {
    name: "Sazerac Variation: Rye + Local Absinthe",
    category: "ancestral",
    ingredients: ["60ml rye whiskey", "¼ tsp local absinthe rinse", "2 dashes Peychaud's bitters"],
    method: "Rinse chilled rocks glass with absinthe. Stir rye and bitters with ice. Strain into glass.",
    glass: "Rocks",
    garnish: "Lemon peel expressed",
    tip: "Exploring local absinthe variations teaches how regional producers create new traditions. Starward or other Australian whisky can replace rye.",
  },
  {
    name: "Bamboo",
    category: "spirit-forward",
    ingredients: ["30ml dry sherry", "30ml dry vermouth", "2 dashes orange bitters"],
    method: "Stir with ice for 10 seconds and strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Orange peel",
    tip: "A pre-Prohibition sherry-based spirit drink. Teaches bartenders to work with fortified wines. Light, elegant, and often overlooked.",
  },
  {
    name: "Vieux Carré",
    category: "ancestral",
    ingredients: ["30ml rye whiskey", "30ml Cognac", "30ml sweet vermouth", "1 dash Angostura bitters", "1 dash Peychaud's bitters"],
    method: "Stir with ice for 10 seconds and strain into a rocks glass with a large ice cube.",
    glass: "Rocks",
    garnish: "Lemon peel and cherry",
    tip: "A New Orleans classic using three spirits. The bitters balance complexity. Teaches layering and moderation. A teaching drink for understanding spirit interactions.",
  },
  {
    name: "Tom Collins",
    category: "highballs",
    ingredients: ["50ml gin", "25ml fresh lemon juice", "15ml sugar syrup", "Top with soda water"],
    method: "Shake gin, lemon, and syrup with ice. Strain into a glass over fresh ice. Top with soda.",
    glass: "Collins glass (tall)",
    garnish: "Lemon wheel and cherry",
    tip: "A 1876 classic. The Collins format is the spirit-lemon-sugar-soda template. Four Pillars Gin is outstanding here. Teaches bartenders the Collins family variations.",
  },
  {
    name: "Gimlet",
    category: "sours",
    ingredients: ["50ml gin", "25ml fresh lime juice (or lime cordial)", "5ml sugar syrup"],
    method: "Shake with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lime wheel",
    tip: "A naval tradition from the Royal Navy. Fresh lime juice is essential. Four Pillars Gin makes this Australian. Simple, balanced, and elegant.",
  },
  {
    name: "Tiki Punch",
    category: "tiki",
    ingredients: ["50ml dark rum", "25ml aged rum", "20ml fresh lime juice", "15ml pineapple juice", "10ml sugar syrup", "1 dash Angostura bitters"],
    method: "Shake hard with crushed ice and serve over fresh crushed ice.",
    glass: "Tiki mug or rocks glass",
    garnish: "Pineapple leaf, lime wheel, cherry",
    tip: "Layered rum and fruit create depth. The bitters add complexity. Teaches how tropical drinks can be balanced, not just sweet.",
  },
  {
    name: "Watermelon Daiquiri",
    category: "sours",
    ingredients: ["50ml white rum", "25ml fresh lime juice", "40ml fresh watermelon juice", "10ml sugar syrup"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Watermelon slice",
    tip: "A summer variation of the classic. Fresh watermelon juice is essential. Teaches bartenders how to adapt formats to seasonal produce. Bundaberg Rum works well.",
  },
  {
    name: "Blood and Sand",
    category: "sours",
    ingredients: ["30ml blended Scotch", "20ml cherry liqueur", "20ml fresh lime juice"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Cherry",
    tip: "A 1920s classic with unexpected cherry-Scotch balance. The ratio is critical. Teaches bartenders that surprising combinations work when balanced.",
  },
  {
    name: "Greyhound",
    category: "highballs",
    ingredients: ["50ml vodka", "120ml fresh grapefruit juice"],
    method: "Build over ice and stir gently.",
    glass: "Highball",
    garnish: "Grapefruit wedge",
    tip: "A simple spirit-juice build. Grapefruit juice quality matters significantly. Use Archie Rose Vodka for an Australian option. Teaches bartenders juice quality impact.",
  },
  {
    name: "Between the Sheets",
    category: "sours",
    ingredients: ["25ml Cognac", "25ml white rum", "25ml Cointreau", "20ml fresh lemon juice"],
    method: "Shake hard with ice and double strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Lemon twist",
    tip: "Three spirits in balance. A teaching moment about equal-parts cocktails. Pre-Prohibition classic.",
  },
  {
    name: "Caipirinha",
    category: "sours",
    ingredients: ["50ml Cachaça", "½ fresh lime (cut into quarters)", "15ml sugar syrup"],
    method: "Press lime gently in a rocks glass. Add syrup and Cachaça. Stir with crushed ice.",
    glass: "Rocks",
    garnish: "Lime wheel",
    tip: "Brazil's national drink. Muddling technique matters — gentle pressing only. Teaches bartenders South American spirits. A cultural gateway drink.",
  },
  {
    name: "Mint Julep",
    category: "highballs",
    ingredients: ["60ml bourbon", "15ml sugar syrup", "8 fresh mint leaves", "Crushed ice"],
    method: "Layer mint and syrup in a silver cup. Add bourbon and stir. Pack with crushed ice. Stir gently.",
    glass: "Silver cup or highball",
    garnish: "Mint sprig",
    tip: "The iconic Kentucky Derby drink. The silver cup is traditional — affects the drinking experience. Teaches bartenders how glassware influences perception.",
  },
  {
    name: "Frozen Daiquiri",
    category: "tiki",
    ingredients: ["60ml white rum", "25ml fresh lime juice", "15ml sugar syrup", "Crushed ice"],
    method: "Blend all ingredients with crushed ice until smooth.",
    glass: "Coupe or tiki glass",
    garnish: "Lime wheel",
    tip: "A blended classic. Consistency is key. This teaches batch preparation for high volume. Bundaberg Rum works well.",
  },
  {
    name: "Blood Orange Martini",
    category: "spirit-forward",
    ingredients: ["60ml gin", "10ml blood orange liqueur", "10ml dry vermouth", "1 dash orange bitters"],
    method: "Stir with ice for 10 seconds and strain into a chilled coupe.",
    glass: "Coupe",
    garnish: "Blood orange peel",
    tip: "A modern variation teaching ingredient sourcing by season. Four Pillars Gin pairs beautifully with citrus.",
  },
];
