/**
 * mastery.ts – Mastery Engine service layer
 *
 * Handles: mastery level progression, spaced repetition scheduling,
 * confidence-accuracy tracking, bridge logic, and the 60-minute spam guard.
 * Elo was retired in audit Phase 5 (2026-10): it was computed but never a
 * reliable signal (Arena's index 40 scored as difficulty 2778).
 */

import type { SupabaseClient } from "@supabase/supabase-js";

// ── Constants ────────────────────────────────────────────────
export const SCENARIO_COUNTS: Record<string, number> = {
  bartending: 10,
  sales: 10,
  management: 20,
};

/**
 * V3: Total modules in the platform. Drives the binary mastery
 * percentage shown on the manager dashboard (mastered / TOTAL_MODULES).
 * Fallback only — syncMasteryToVenueStaff() prefers the live count from
 * the modules table. Platform has 40 modules (see lib/verify-questions.ts).
 */
const V3_TOTAL_MODULES = 40;

/**
 * V3: Module category mapping. Mirrors supabase/migrations/20260421_1_create_modules.sql
 * plus the modules 21-40 added in lib/module-navigator.ts's default catalog.
 * Used by the Manager dashboard StaffBadges to compute category mastery.
 * Fallback only — syncMasteryToVenueStaff() prefers live categories from the modules table.
 */
const V3_MODULE_CATEGORIES: Record<number, "technical" | "service" | "compliance"> = {
  1: "technical", 2: "technical", 3: "technical", 4: "technical",
  5: "technical", 6: "technical", 7: "technical",
  8: "service", 9: "service", 10: "service", 11: "service",
  12: "service", 13: "service", 14: "service",
  15: "compliance", 16: "compliance", 17: "compliance",
  18: "compliance", 19: "compliance", 20: "compliance",
  21: "compliance", 22: "compliance", 23: "service", 24: "compliance",
  25: "compliance", 26: "technical", 27: "technical", 28: "technical",
  29: "service", 30: "service", 31: "compliance", 32: "technical",
  33: "technical", 34: "technical", 35: "compliance", 36: "service",
  37: "service", 38: "service", 39: "technical", 40: "service",
};

// Pass mark (15/25), mastery streak (3) and spam guard (60 min) live in
// the record_attempt() Postgres function — see recordAttempt() below.

export type ConfidenceLevel = "low" | "medium" | "high";

/**
 * scenario_mastery's real key is (user_id, module, scenario_type, scenario_index) —
 * see supabase/migrations/20260820_scenario_mastery_scenario_type.sql. Quiz
 * (mark_module_mastered() in SQL) always writes scenario_index=0; Arena roleplay
 * (recordAttempt) always writes scenario_index=40; Scenario Training
 * (recordAttempt, descriptor) writes the real trainer-data.ts content index.
 * Without scenario_type, Quiz and the first Scenario Training scenario for
 * modules 1-3 collide on the same (user, module, 0) row.
 */
export type ScenarioType = "quiz" | "descriptor" | "roleplay";

export type MasteryRow = {
  id: string;
  user_id: string;
  module: string;
  scenario_type: ScenarioType;
  scenario_index: number;
  mastery_level: number;
  consecutive_correct: number;
  total_attempts: number;
  total_score_points: number;
  best_score: number;
  last_score: number;
  last_attempt_at: string | null;
  next_review_at: string | null;
  last_confidence: ConfidenceLevel | null;
  high_confidence_incorrect: number;
  low_confidence_correct: number;
  consecutive_fails: number;
};

export type MasteryProgress = {
  /** Completion % – distinct scenarios at mastery_level >= 1 / total */
  completion: number;
  /** Mastery % – distinct scenarios at mastery_level == 3 / total */
  mastery: number;
  /** Total unique scenarios attempted */
  scenariosAttempted: number;
  /** Total unique scenarios mastered (level 3) */
  scenariosMastered: number;
  /** Average score across all attempts */
  avgScore: number;
  /** Total attempts (includes repeats) */
  totalAttempts: number;
};

export type SpacedRepetitionItem = {
  module: string;
  scenarioType: ScenarioType;
  scenarioIndex: number;
  masteryLevel: number;
  nextReviewAt: string;
  lastScore: number;
  consecutiveFails: number;
};

export type RecordAttemptInput = {
  userId: string;
  module: string;
  moduleId?: number; // numeric module id for new 20-module system
  /**
   * "quiz" never goes through recordAttempt() — that write path is
   * the verify quiz only. recordAttempt() callers are Scenario
   * Training (descriptor) and AI Arena (roleplay).
   */
  scenarioType: Exclude<ScenarioType, "quiz">;
  scenarioIndex: number;
  overallScore: number;
  confidence: ConfidenceLevel;
  /**
   * Idempotency key, generated by the client once per submission and reused
   * on retry: a repeated id returns the first result and records nothing.
   */
  attemptId: string;
  /** The grader's feedback, stored so a retry can be answered without regrading. */
  evaluation?: unknown;
  /**
   * Caller's own pass/fail verdict, when its pass mark differs from
   * PASS_SCORE (15/25). Arena passes at 75/100, but its score arrives here as
   * score/4, and PASS_SCORE (15/25) would count 60-74 as correct — setting
   * the sticky is_mastered flag for attempts the user was told they failed.
   * Omit to use the 15/25 pass mark.
   */
  passed?: boolean;
};

// Map numeric moduleId to legacy string for modules 1-3 (backward compat)
const LEGACY_MODULE_NAMES: Record<number, string> = {
  1: "bartending",
  2: "sales",
  3: "management",
};

export function moduleIdToString(moduleId: number): string {
  return LEGACY_MODULE_NAMES[moduleId] ?? `module_${moduleId}`;
}

// Reverse of moduleIdToString() — resolves a scenario_mastery `module`
// string back to its numeric catalog id. Used by consumers (Phase 5,
// v4-migration-plan/00-bug-batch-plan.md item 11) that need to look up real
// module metadata (title, category) from the `modules` table/allModules for
// Quiz and Arena roleplay rows, where the numeric id genuinely identifies
// matching catalog content. NOT safe to use for resolving a title for
// "descriptor" (Scenario Training) rows on modules 1-3 — LEGACY_MODULE_NAMES
// only exists so those legacy string rows can reuse the numeric catalog's
// access-gate plumbing (see LEGACY_MODULE_ID in training/save/route.ts); the
// catalog content actually sitting at ids 1/2/3 ("Beer Pouring",
// "Wine Service", "Cocktail Fundamentals") is unrelated to the
// Scenario Training content shown under the "sales"/"management" labels.
const LEGACY_MODULE_IDS: Record<string, number> = { bartending: 1, sales: 2, management: 3 };

export function moduleStringToId(moduleStr: string): number | null {
  if (moduleStr in LEGACY_MODULE_IDS) return LEGACY_MODULE_IDS[moduleStr];
  const match = /^module_(\d+)$/.exec(moduleStr);
  return match ? Number(match[1]) : null;
}

export type RecordAttemptResult = {
  masteryLevel: number;
  previousLevel: number;
  levelChanged: boolean;
  spamGuarded: boolean;
  nextReviewAt: string;
  isBridge: boolean; // should next scenario be easier?
  consecutiveFails: number;
  confidenceAccuracy: "expert" | "lucky-guesser" | "student" | "liability";
  /** True when this attempt id had already been recorded; nothing changed. */
  replayed: boolean;
  /** On a replay, the evaluation stored with the first recording. */
  evaluation?: unknown;
};

// ── Core: Record an attempt ──────────────────────────────────
//
// The rules (pass mark 15/25, 3 in a row to master, 60-minute spam guard,
// spaced-repetition review dates) run inside the record_attempt()
// Postgres function (supabase/migrations/20261002_atomic_attempts_and_verify_quiz.sql),
// in one transaction with the mastery row locked. This used to be a
// read-then-upsert here, which lost updates under concurrent requests and
// counted a retried submit twice (audit 2026-09-30, M1/M2).

export async function recordAttempt(
  admin: SupabaseClient,
  input: RecordAttemptInput,
): Promise<RecordAttemptResult> {
  const moduleName = input.moduleId ? moduleIdToString(input.moduleId) : input.module;

  const { data, error } = await admin.rpc("record_attempt", {
    p_attempt_id: input.attemptId,
    p_user_id: input.userId,
    p_module: moduleName,
    p_module_id: input.moduleId ?? null,
    p_scenario_type: input.scenarioType,
    p_scenario_index: input.scenarioIndex,
    p_score: Number.isFinite(input.overallScore) ? input.overallScore : 0,
    p_passed: input.passed ?? null,
    p_confidence: input.confidence,
    p_evaluation: input.evaluation ?? null,
  });

  if (error) {
    if (error.message.includes("ATTEMPT_ID_CONFLICT")) throw new AttemptIdConflictError();
    throw error;
  }
  return data as RecordAttemptResult;
}

/** The attempt id was already used for a different scenario or user. */
export class AttemptIdConflictError extends Error {
  constructor() {
    super("Attempt id already used for a different attempt.");
    this.name = "AttemptIdConflictError";
  }
}

/**
 * A previously recorded attempt with this id, for answering a retried
 * request without grading it again. Null when the id is new, or belongs to
 * another user.
 */
export async function findRecordedAttempt(
  admin: SupabaseClient,
  userId: string,
  attemptId: string,
): Promise<{ result: RecordAttemptResult; evaluation: unknown } | null> {
  const { data, error } = await admin
    .from("training_attempts")
    .select("user_id, result, evaluation")
    .eq("id", attemptId)
    .maybeSingle();
  if (error || !data || data.user_id !== userId) return null;
  // result is filled in by the same transaction that inserts the row, so an
  // empty object can't be seen; guard anyway.
  if (!data.result || typeof data.result !== "object" || !("masteryLevel" in data.result)) return null;
  return { result: { ...(data.result as RecordAttemptResult), replayed: true }, evaluation: data.evaluation };
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * The client's attempt id when it sent a valid one, else a fresh id (older
 * cached clients don't send one; their attempts still record, just without
 * retry protection).
 */
export function resolveAttemptId(raw: unknown): { id: string; fromClient: boolean } {
  if (typeof raw === "string" && UUID_PATTERN.test(raw)) return { id: raw.toLowerCase(), fromClient: true };
  return { id: crypto.randomUUID(), fromClient: false };
}

// ── V3: Binary mastery write ─────────────────────────────────
//
// Called once per verify quiz run that reaches the required streak — by the
// advance_verify_attempt() Postgres function, in the same transaction that
// closes the run. Sets is_mastered = true and never reverses it.

export type MarkMasteredResult = {
  isMastered: true;
  alreadyMastered: boolean;
};


// ── Get mastery progress for a module ────────────────────────

export async function getMasteryProgress(
  admin: SupabaseClient,
  userId: string,
  module: string,
  scenarioType: ScenarioType,
): Promise<MasteryProgress> {
  const { data: rows } = await admin
    .from("scenario_mastery")
    .select("mastery_level, total_attempts, total_score_points")
    .eq("user_id", userId)
    .eq("module", module)
    .eq("scenario_type", scenarioType)
    .is("archived_at", null);

  const total = SCENARIO_COUNTS[module] ?? 10;
  const masteryRows = (rows ?? []) as Pick<MasteryRow, "mastery_level" | "total_attempts" | "total_score_points">[];

  const attempted = masteryRows.length;
  const mastered = masteryRows.filter((r) => r.mastery_level >= 3).length;
  const passed = masteryRows.filter((r) => r.mastery_level >= 1).length;
  const totalAttempts = masteryRows.reduce((s, r) => s + r.total_attempts, 0);
  const totalScorePoints = masteryRows.reduce((s, r) => s + r.total_score_points, 0);
  const avgScore = totalAttempts > 0
    ? Math.round((totalScorePoints / totalAttempts) * 10) / 10
    : 0;

  return {
    completion: Math.min(Math.round((passed / total) * 100), 100),
    mastery: Math.min(Math.round((mastered / total) * 100), 100),
    scenariosAttempted: attempted,
    scenariosMastered: mastered,
    avgScore,
    totalAttempts,
  };
}

// ── Get spaced repetition queue (due for review) ─────────────

export async function getReviewQueue(
  admin: SupabaseClient,
  userId: string,
  module?: string,
): Promise<SpacedRepetitionItem[]> {
  const now = new Date().toISOString();

  // Not filtered by scenario_type — a review row can be Quiz, Scenario
  // Training, or Arena content; scenario_type is returned so callers (e.g.
  // ProgressScreen's "Up Next For Review" labels, Phase 5) can branch the
  // display text per type instead of assuming every row is descriptor
  // content.
  let query = admin
    .from("scenario_mastery")
    .select("module, scenario_type, scenario_index, mastery_level, next_review_at, last_score, consecutive_fails")
    .eq("user_id", userId)
    .is("archived_at", null)
    .lte("next_review_at", now)
    .order("next_review_at", { ascending: true })
    .limit(20);

  if (module) {
    query = query.eq("module", module);
  }

  const { data: rows } = await query;

  return (rows ?? []).map((r) => ({
    module: r.module as string,
    scenarioType: r.scenario_type as ScenarioType,
    scenarioIndex: r.scenario_index as number,
    masteryLevel: r.mastery_level as number,
    nextReviewAt: r.next_review_at as string,
    lastScore: r.last_score as number,
    consecutiveFails: r.consecutive_fails as number,
  }));
}

// ── Get all mastery rows for a user+module (for detail views) ──

export async function getScenarioMasteryDetails(
  admin: SupabaseClient,
  userId: string,
  module: string,
): Promise<MasteryRow[]> {
  const { data } = await admin
    .from("scenario_mastery")
    .select("*")
    .eq("user_id", userId)
    .eq("module", module)
    .is("archived_at", null)
    .order("scenario_index", { ascending: true });

  return (data ?? []) as MasteryRow[];
}

// ── Category-average mastery rollup ──────────────────────────
//
// Phase 4 (v4-migration-plan/00-bug-batch-plan.md, item 10). Averages
// moduleProgress[m.id].mastery across every module in `allModules` matching
// `category`, defaulting to 0 when the category has no modules. This was
// hand-duplicated 3x on desktop (ProgressOverview.tsx::catAvg(),
// PreShiftHome.tsx::getCategoryMastery(), BadgesView.tsx::catAvg()) and NOT
// implemented server-side at all — GET /api/training/progress's legacy
// `mastery: {bartending, sales, management}` field was actually
// getMasteryProgress() run per legacy-string-module, a different and
// unrelated calculation that happened to share a field name. New callers
// (mobile or desktop) should read this helper — or the `mastery` field on
// GET /api/training/progress, which now calls it — rather than
// re-deriving the average locally a 4th time.
export function categoryMasteryAverage(
  allModules: { id: number; category: string }[],
  moduleProgress: Record<number, { mastery: number }>,
  category: string,
): number {
  const mods = allModules.filter((m) => m.category === category);
  if (mods.length === 0) return 0;
  const avg = mods.reduce((sum, m) => sum + (moduleProgress[m.id]?.mastery ?? 0), 0) / mods.length;
  return Math.round(avg);
}

// ── Per-scenario_type module mastery (Phase 3c, mobile bug-fix plan) ────
//
// GET /api/training/progress's own `moduleProgress[mod.id].mastery` blends
// every scenario_type recorded against a module_id together — a module's
// quiz row (scenario_index=0) and its Arena roleplay row (scenario_index=40)
// both land in the same module_id bucket and get averaged as one number.
// That's the right shape for the single top-level ring per category, but
// not precise enough for the Me page's "Modules"/"AI Scenarios" sub-bars,
// which need quiz and roleplay told apart. This isolates one scenario_type
// at a time, in the same shape categoryMasteryAverage() already expects, so
// callers compose it the same way: categoryMasteryAverage(allModules,
// moduleMasteryByType(rows, allModules, counts, "quiz"), category).
//
// The third sub-bar, "Scenarios" (Category Simulations), isn't computed
// here — it's legacy-string-keyed (trainer-data.ts's 3-module bank, not
// module_id), already covered by the existing per-legacy-module
// getMasteryProgress(admin, userId, module, "descriptor") call every caller
// of GET /api/training/progress already makes for masteryByModule.
export function moduleMasteryByType(
  rows: Array<{ module_id: number | null; scenario_type?: ScenarioType | null; mastery_level: number; is_mastered?: boolean | null }>,
  allModules: { id: number }[],
  scenarioCounts: Record<string, number>,
  type: ScenarioType,
): Record<number, { mastery: number }> {
  const byModuleId: Record<number, typeof rows> = {};
  for (const row of rows) {
    if (row.module_id == null || row.scenario_type !== type) continue;
    (byModuleId[row.module_id] ??= []).push(row);
  }

  const result: Record<number, { mastery: number }> = {};
  for (const mod of allModules) {
    const modRows = byModuleId[mod.id] ?? [];
    const mastered = modRows.filter((r) => r.mastery_level >= 3).length;
    const hasVerified = modRows.some((r) => r.is_mastered === true);
    const scenarioTotal = scenarioCounts[`module_${mod.id}`] ?? 10;
    result[mod.id] = {
      mastery: hasVerified ? 100 : modRows.length > 0 ? Math.round((mastered / scenarioTotal) * 100) : 0,
    };
  }
  return result;
}

// ── Sync mastery data to venue_staff for management dashboard ──

// Follows the linked account only (see lib/staff-link.ts). Matching by email
// here used to push a user's progress onto any roster row carrying their
// address, linked to them or not.
export async function syncMasteryToVenueStaff(
  admin: SupabaseClient,
  userId: string,
): Promise<void> {
  const { data: staffRows } = await admin
    .from("venue_staff")
    .select("id")
    .eq("staff_user_id", userId);

  if (!staffRows || staffRows.length === 0) return;

  // Dynamic module discovery: query the modules table for live totals and categories.
  // Falls back to V3 hardcoded constants if the table is empty (e.g. pre-migration).
  const { data: moduleRows } = await admin
    .from("modules")
    .select("id, category");

  const activeModules = (moduleRows ?? []) as Array<{ id: number; category: string }>;
  const totalModules = activeModules.length > 0 ? activeModules.length : V3_TOTAL_MODULES;

  const categoryMap = new Map<number, string>(activeModules.map((m) => [m.id, m.category]));
  const totalTechnical = activeModules.length > 0
    ? activeModules.filter((m) => m.category === "technical").length
    : Object.values(V3_MODULE_CATEGORIES).filter((c) => c === "technical").length;

  // V3 binary mastery aggregation.
  // quiz rows: is_mastered set by the verify quiz (module gate).
  // roleplay rows: is_mastered set by an Arena pass (service gate).
  // service_score = 80% quiz mastery + 20% roleplay mastery.
  const { data: allMastery } = await admin
    .from("scenario_mastery")
    .select("module, module_id, scenario_type, is_mastered, high_confidence_incorrect, low_confidence_correct")
    .eq("user_id", userId)
    .is("archived_at", null);

  const rows = (allMastery ?? []) as Array<{
    module: string;
    module_id: number | null;
    scenario_type: ScenarioType;
    is_mastered: boolean;
    high_confidence_incorrect: number | null;
    low_confidence_correct: number | null;
  }>;

  const attemptedIds = new Set<number>();
  const masteredIds = new Set<number>();         // verify quiz passed
  const roleplayMasteredIds = new Set<number>(); // Arena passed
  let totalHighConfidenceIncorrect = 0;
  let totalLowConfidenceCorrect = 0;
  for (const r of rows) {
    if (r.module_id == null) continue;
    attemptedIds.add(r.module_id);
    if (r.scenario_type === "quiz" && r.is_mastered) masteredIds.add(r.module_id);
    if (r.scenario_type === "roleplay" && r.is_mastered) roleplayMasteredIds.add(r.module_id);
    totalHighConfidenceIncorrect += r.high_confidence_incorrect ?? 0;
    totalLowConfidenceCorrect += r.low_confidence_correct ?? 0;
  }

  // "Confidence Mismatch" signal for the manager console (Overview KPI tile,
  // Predictive/Skill-Gaps panels): what fraction of confidence-tagged
  // attempts were a high-confidence wrong answer vs. a low-confidence right
  // one. Only high_confidence_incorrect/low_confidence_correct are counted
  // (matches recordAttempt()'s own confidence-accuracy buckets, see
  // classifyConfidenceAccuracy above) — undefined when the user has no
  // confidence-tagged attempts yet, rather than a misleading 0.
  const confidenceMismatchTotal = totalHighConfidenceIncorrect + totalLowConfidenceCorrect;
  const highConfidenceIncorrectRatio = confidenceMismatchTotal > 0
    ? totalHighConfidenceIncorrect / confidenceMismatchTotal
    : undefined;

  const totalAttempted = attemptedIds.size;
  const totalMastered = masteredIds.size;

  // product_score = % of technical-category modules mastered
  let technicalMastered = 0;
  for (const id of masteredIds) {
    const cat = categoryMap.get(id) ?? V3_MODULE_CATEGORIES[id];
    if (cat === "technical") technicalMastered++;
  }
  const productScore = totalTechnical > 0
    ? Math.round((technicalMastered / totalTechnical) * 100)
    : 0;

  const overallProgress = Math.round((totalMastered / totalModules) * 100);
  const roleplayProgress = Math.round((roleplayMasteredIds.size / totalModules) * 100);
  // Weighted service score: 80% from quiz mastery, 20% from Arena roleplay completion
  const computedServiceScore = Math.round(overallProgress * 0.8 + roleplayProgress * 0.2);

  let masteryStatus = "not-started";
  if (totalMastered >= totalModules) {
    masteryStatus = "mastered";
  } else if (totalAttempted > 0) {
    masteryStatus = "in-progress";
  }

  // Completion: share of modules the user has started at all. totalAttempted
  // counts distinct modules, so this used to divide modules by ~10× the
  // module count and could never pass 10% (audit 2026-09-30, M5).
  const completionPct = Math.min(Math.round((totalAttempted / totalModules) * 100), 100);

  const updatePayload = {
    progress: overallProgress,
    mastery_status: masteryStatus,
    scenarios_mastered: totalMastered,
    scenarios_attempted: totalAttempted,
    product_score: productScore,
    service_score: computedServiceScore,
    module_completion_pct: completionPct,
    module_mastery_pct: overallProgress,
    last_active_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...(highConfidenceIncorrectRatio !== undefined ? { high_confidence_incorrect_ratio: highConfidenceIncorrectRatio } : {}),
  };

  await admin
    .from("venue_staff")
    .update(updatePayload)
    .eq("staff_user_id", userId);
}
