-- Arena Seed Scenarios: one deterministic roleplay per module (scenario_index = 40)
-- Used by the Arena (Stage 4) as fixed starting points for AI roleplay.
-- The opening_line is shown verbatim to the user; context + goal guide the AI actor.

INSERT INTO scenarios (module_id, scenario_index, scenario_type, prompt, content, difficulty)
VALUES
(1, 40, 'roleplay', 'Handle a flat beer complaint mid-rush.',
  '{"opening_line": "Mate, this schooner is mostly head and it tastes flat. Can you fix this?", "context": "The pub is packed and you are mid-rush. The guest''s glass feels warm to the touch and they are visibly annoyed.", "goal": "Identify the cause (warm glass or line issue), replace the drink correctly, and manage the guest''s frustration professionally."}',
  4),
(2, 40, 'roleplay', 'Help a guest transition from Cabernet to an Australian Shiraz.',
  '{"opening_line": "I usually drink Cabernet but I want to try an Australian Shiraz. Is the one from the Barossa very different?", "context": "A couple is looking at the wine list. One is a confident heavy-red drinker curious about local varietals.", "goal": "Explain the profile difference between Barossa Shiraz and Cabernet in clear, appealing terms and make a confident recommendation."}',
  3),
(3, 40, 'roleplay', 'Recommend a cocktail to a vague, high-energy hens party guest.',
  '{"opening_line": "I want something sweet but strong, not too fruity, maybe with gin? But I hate tonic. Just make me something good!", "context": "It is 9 PM on a Saturday, the bar is three-deep and a rowdy hens party has arrived. You are under pressure.", "goal": "Read the brief quickly, make a confident recommendation, and move the guest through efficiently without losing the energy of the moment."}',
  4),
(4, 40, 'roleplay', 'Confirm a complex coffee order during the morning rush.',
  '{"opening_line": "Can I get a large skinny cap, extra hot, and a flat white on soy?", "context": "It is 8 AM on a weekday. The customer is shouting over the grinder and you already have five dockets on the machine.", "goal": "Confirm the order clearly and efficiently, manage the queue professionally, and maintain quality under time pressure."}',
  3),
(5, 40, 'roleplay', 'Handle a guest trying to help while you are clearing a heavy table.',
  '{"opening_line": "Here, let me help — I''ll hand you these plates!", "context": "You are clearing a large table in the bistro with heavy schooner glasses, wine glasses, and a half-full water jug. A well-meaning guest tries to hand you a stack of unstable plates while you are mid-lift.", "goal": "Politely decline the help, protect your load, and keep the guest feeling appreciated rather than dismissed."}',
  2),
(6, 40, 'roleplay', 'Manage a broken glass and spill near a high-traffic area.',
  '{"opening_line": "Excuse me, someone just dropped a glass near the toilets!", "context": "You are the only staff member on the floor, carrying three drinks, and there is a broken glass and a spilled drink near the entrance to the toilets.", "goal": "Prioritise guest safety, secure the hazard, communicate clearly, and manage your drinks without creating a secondary spill."}',
  4),
(7, 40, 'roleplay', 'Prioritise a barback emergency during slammed service.',
  '{"opening_line": "Oi! We are out of clean schooner glasses and the ice bin is empty!", "context": "The main bar is getting slammed and the bartender is yelling at you. You are currently restocking the coolroom.", "goal": "Correctly prioritise ice over glasses (safety), communicate your plan to the bartender, and execute efficiently within 60 seconds."}',
  4),
(8, 40, 'roleplay', 'Acknowledge two different guests simultaneously during a Guinness pour.',
  '{"opening_line": "Hi, are you serving? We have been waiting a while.", "context": "A local regular and a group of lost-looking tourists arrive at the same time. You are mid-pour on a Guinness and cannot leave your station.", "goal": "Acknowledge both parties warmly within three seconds, set expectations, and avoid abandoning your pour."}',
  3),
(9, 40, 'roleplay', 'Move a table of eight along with the kitchen closing in 15 minutes.',
  '{"opening_line": "We are still chatting — can you give us a few more minutes?", "context": "You are serving a table of eight. Two guests are ready to order but six are deep in conversation with menus closed. Kitchen closes in 15 minutes.", "goal": "Move the table along professionally and warmly without making anyone feel rushed or unwelcome."}',
  4),
(10, 40, 'roleplay', 'Check in on a guest who has finished their wine while you are en route elsewhere.',
  '{"opening_line": "(The guest is looking around the room after finishing their Shiraz.)", "context": "You notice a guest in the lounge has finished their drink and is scanning for staff. You are currently heading to the bistro with another table''s order.", "goal": "Acknowledge the guest, communicate your return plan clearly, and follow through — demonstrating anticipatory service without dropping your current task."}',
  3),
(11, 40, 'roleplay', 'Handle an angry guest who waited 45 minutes for a parmy.',
  '{"opening_line": "Mate, we ordered our parmys 45 minutes ago. Those guys next to us sat down after us and they are already eating. What is going on?", "context": "It is a busy Sunday session in the bistro. The guest is frustrated and has come to the bar to confront you directly.", "goal": "Empathise genuinely, investigate without making excuses, and resolve the issue — never blame the kitchen in front of the guest."}',
  5),
(12, 40, 'roleplay', 'Upsell a premium craft lager over the house pour.',
  '{"opening_line": "What lagers do you have on tap?", "context": "The guest is asking about lagers. You have a standard house pour but also a premium local craft lager that was just tapped, costing $2 more.", "goal": "Steer the guest toward the premium option naturally and confidently without being pushy."}',
  3),
(13, 40, 'roleplay', 'Handle a VIP regular who expects their booth on a fully booked night.',
  '{"opening_line": "Hey, I am here for my usual booth. You know I always sit there.", "context": "A VIP regular who always spends big has arrived without a booking on a fully committed Saturday night. Their usual booth is occupied by a family.", "goal": "Protect the seated guests, retain the VIP''s goodwill, and find a genuine solution — no empty promises."}',
  5),
(14, 40, 'roleplay', 'Turn away a booking for 20 people on a fully committed phone line.',
  '{"opening_line": "Hi, I''d like to book a table for twenty people tonight please.", "context": "The phone is ringing during the lunch rush and your system shows you are already at capacity for tonight.", "goal": "Deliver the bad news warmly, offer genuine alternatives, and protect the relationship for a future booking."}',
  3),
(15, 40, 'roleplay', 'Refuse service to a stumbling regular at 11:30 PM.',
  '{"opening_line": "Mate, just give us one more schooner of New and a shot of JD. I am fine, I promise!", "context": "It is Friday night, 11:30 PM. A regular is stumbling and leaning heavily against the counter, slapping down a $50 note.", "goal": "Refuse service firmly, compassionately, and in compliance with RSA — without escalating or humiliating the guest."}',
  5),
(16, 40, 'roleplay', 'Intercept a gluten contamination before it reaches a coeliac guest.',
  '{"opening_line": "(You notice the Gluten Free burger is on the same plate as a regular bun before it leaves the pass.)", "context": "You are about to run a tray of food and spot the error. The guest is a known coeliac.", "goal": "Stop the food, communicate clearly with the kitchen, and manage the guest''s wait professionally without alarming them unnecessarily."}',
  5),
(17, 40, 'roleplay', 'De-escalate a loud group causing discomfort in the TAB area.',
  '{"opening_line": "Oi, we are fine! We are just having a good time, relax!", "context": "A group in the TAB area are swearing and leaning over other patrons'' tables. Other guests are visibly uncomfortable. You have approached to settle them down.", "goal": "De-escalate without confrontation, set clear expectations, and protect the comfort of the surrounding guests."}',
  5),
(18, 40, 'roleplay', 'Take command of a room during a fire alarm on a busy Friday night.',
  '{"opening_line": "Is this a drill? Should we leave our drinks?", "context": "The fire alarm starts ringing during a packed Friday night service. Patrons are confused — some are trying to finish their drinks, others are heading back for bags.", "goal": "Take command calmly and authoritatively, direct all guests to the exit, and enforce evacuation without creating panic."}',
  5),
(19, 40, 'roleplay', 'Handle a $100 till discrepancy at 2 AM with your lift waiting outside.',
  '{"opening_line": "(You have just completed the final till count and you are $100 short.)", "context": "It is 2 AM at closing time. You have found a $100 discrepancy. Your lift home is waiting outside and the alarm needs to be set.", "goal": "Follow correct protocol — document and report the discrepancy before leaving. Never leave a venue short without a written record."}',
  4),
(20, 40, 'roleplay', 'Address a co-worker who is consistently over-pouring and voiding staff drinks.',
  '{"opening_line": "(You have noticed your co-worker is consistently over-pouring spirits and forgetting to ring up staff drinks for their mates.)", "context": "This has been happening repeatedly and is hitting the venue''s gross profit. You need to decide whether to address it directly or escalate to management.", "goal": "Address the issue professionally — with the co-worker first if appropriate, escalating to management if needed. Protect the venue without destroying the working relationship."}',
  4);
